version: "3"

services:

  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=Root@2021
      - MYSQL_DATABASE=candidate
      - MYSQL_USER=user
      - MYSQL_PASSWORD=User@2021
    ports:
      - "3306:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=Root@2021 --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 10
    networks:
      docker-net:
        ipv4_address: ${IP_SQL}

  candidate:
    container_name: candidate
    image: candidate
    ports:
      - "8081:8081"
    networks:
      docker-net:
        ipv4_address: ${IP_CANDIDATE}
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${IP_SQL}:3306/P9?serverTimezone=UTC
    restart: on-failure
    depends_on:
      mysql:
        condition: service_healthy

  client-ui:
    container_name: client-ui
    image: client-ui
    ports:
      - "8083:8083"
    networks:
      docker-net:
        ipv4_address: ${IP_CLIENT_UI}

networks:
  docker-net:
    external: true
    driver: bridge
